spring.application.name=youtubeCLI
spring.main.web-application-type = none
spring.shell.script.enabled=true
spring.shell.interactive.enabled=true
logging.level.org.springframework.shell=WARN

github.token={YOUR_GITHUB_TOKEN}
Gemini.API.Key={YOUR_AI_API_KEY}

# Set the log format
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n

# Set default log level
logging.level.root=INFO

org.gradle.java.installations.auto-detect=true

#project-name=projects/735336057674
#project-number=projects/735336057674
