spring.application.name=youtubeCLI
spring.main.web-application-type = none
spring.shell.script.enabled=true
spring.shell.interactive.enabled=false
logging.level.org.springframework.shell=DEBUG

github.token=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
Gemini.API.Key=AIzaSyBEJnoRfY-7oNyg0oY8KHUcu6hg5Dm2w7s


#project-name=projects/735336057674
#project-number=projects/735336057674
